name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: secrets echo
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          FLOW_DB_ID: ${{ secrets.FLOW_DB_ID }}
          ASSETS_DB_ID: ${{ secrets.ASSETS_DB_ID }}
          TEMPLATE_DB_ID: ${{ secrets.TEMPLATE_DB_ID }}
        run: echo $NOTION_TOKEN
